### ISSUE TITLE
Errors on depot-archive creation

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode-world#242]
The following depot recipes must be fixed or removed.

- [x] genodelabs/raw/qt5_avplay
- [x] genodelabs/src/qt5_avplay
- [x] genodelabs/bin/x86_64/solo5
- [x] genodelabs/bin/x86_64/fb_upscale
- [x] genodelabs/bin/x86_64/io_editor
- [x] genodelabs/bin/x86_64/qt5_avplay
- [x] genodelabs/bin/x86_64/gtotp_report
- [x] genodelabs/bin/x86_64/input_normalizer
- [x] genodelabs/pkg/terminal_editor

**Comment by nfeske** [comment]
Most of these depot archives are related to contributions by @ehmry. How should we go about them? Since the code is not actively maintained and apparently unused at large, should we remove it? @ehmry how do you think about it?

@cproc I'd like to preserve the qt5_avplay as an component-composition example (embedding GUI application inside a Qt app). So I think to would be worthwhile to fix it. May you have a look?

**Comment by ehmry** [comment]
I'm okay with removing my old recipe files, they will remain the git history.

**Comment by nfeske** [comment]
Thanks for the quick reply.

How do you think about the actual build issues? Should we remove the code along with the recipes, or should we keep it even though there are build errors?

E.g., regarding the input_normalizer, I sense that it is not worth fixing because "Input" services play no longer any role since we moved to the event-session interface. The fb_upscale case is similar. With the move of most clients to the GUI session, it is no longer usable in practice.

**Comment by ehmry** [comment]
Thats true, I will check what builds and make a patch to remove what is outdated.

**Comment by ehmry** [comment]
Patch at 301474b7e886445c726c4d92642fa90e0828c7c2.

**Comment by nfeske** [comment]
Thanks @ehmry, I merged your commit just now.

**Comment by chelmuth** [comment]
The _io_editor_ packaging still fails, which raises the question: Should it be removed or fixed? @ehmry?

**Comment by ehmry** [comment]
Remove for now, cb6607bf39c79fa908e75aa2da21f694692963ad.

**Comment by chelmuth** [comment]
Thanks, merged the commit and added the `Fixes` tag.
